
server:
  port:8181

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa
    username: choyejin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
#    show-sql: true # 자동 생성된 쿼리를 보여주는 옵션
    # 로그가 나올 때 어떤 디비에 맞게 나오는지 설정
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update #????? none?? ??? ?? ???.
    properties:
      hibernate:
        format_sql: true #sql을 줄바꿈해서 이쁘게 출력
    database: mysql # 디비 계열 설정

# 시간이랑 같이 찍힌다
    logging.level:
      org.hibernate.SQL: debug